name: FatJar bauen

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  job-fatjar:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Execution-Bit für Maven-Wrapper setzen
      run: chmod u+x mvnw
    - name: Maven-Installation überprüfen
      run: ./mvnw --version       
    - name: FatJar-Datei mit Maven bauen
      run: ./mvnw --batch-mode clean package
    - name: FatJar-Datei veröffentlichen
      uses: actions/upload-artifact@v4
      with:
        name: Vokalersetzung_FatJar_java
        path: target/vokalersetzung-*-SNAPSHOT.jar
        if-no-files-found: error
        retention-days: 3
